project/dashboard/urls.py
from django.urls import path, re_path
from . import views
from .views import (
    PageDeleteView,
    PageCreateView,
    AccountCreateView,
    AccountUpdateView,
    AccountDeleteView,
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostLanguageListView,
    PostLanguageCreateView,
    PostLanguageUpdateView,
    PostLanguageDeleteView,

    CommentListView
)

from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='home'),
    path('informaion_site/', views.edite_informaion, name='informaion_site'),
    path('profile/', views.profile, name='profile'),
    path("logout/", views.auth_logout, name="logout"),
###
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete', views.delete, name='delete'),

###
    path('service/', views.services, name='services'),
    path('service/edite/<int:id>/', views.services_edite, name='services_edite'),
    path('service/delete/<int:id>/', views.services_delete, name='services_delete'),
    path('service/create/', views.services_add, name='services_add'),


##
    path('page/', views.page, name='page'),
    path('page/about', views.page_about, name='page_about'),

    path('page/create/', PageCreateView.as_view(), name='page_add'),
    path('page/edite/<int:id>/', views.page_edite, name='page_edite'),
 #   path('page/delete/<int:id>/', views.page_delete, name='page_delete'),
    path('page/delete/<int:pk>/', PageDeleteView.as_view(), name='page_delete'),

##
    path('aluser/<int:pk>', views.AEditUser.as_view(), name='user_edite'),
    path('aluser/', views.user_show, name='accounts'),
   # path('create_use/', views.create_user, name='create_user_form'),
   
    path('account/create/', AccountCreateView.as_view(), name='accounts_create'),
    path('account/update/<int:pk>/', AccountUpdateView.as_view(), name='accounts_update'),
    path('account/delete/<int:pk>/', AccountDeleteView.as_view(), name='accounts_delete'),
    
    path('alvuser/<int:pk>', views.ALViewUser.as_view(), name='alvuser'),
   # path('aeuser/<int:pk>', views.AEditUser.as_view(), name='aeuser'),
   # path('aduser/<int:pk>', views.ADeleteUser.as_view(), name='aduser'),



    #### posts
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
  # path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    #path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),

    path('post/update/<int:id>/', views.post_update, name='post_update'),
    path('post/delete/<int:id>/', views.post_delete, name='post_delete'),

    path('posts/translation/', PostLanguageListView.as_view(), name='posts_language'),
    path('post/add/translation/<int:id>/', PostLanguageCreateView.as_view(), name='post_language_create'),
    path('post/update/translation/<int:pk>/', views.post_language_update, name='post_language_update'),
    path('post/delete/translation/<int:pk>/', views.post_language_delete, name='post_language_delete'),

        # Comments Urls
    path('comment/', CommentListView.as_view(), name='comments'),
    path('comments/delete/<int:id>/', views.comment_delete, name='comment_delete'),



###  brands
    path('brands/', views.brands, name='brands'),
    path('brands/delete/<int:id>/', views.brands_delete, name='brands_delete'),
    path('brands/create/', views.brands_add, name='brands_add'),

    
]

project/post/urls.py
from django.urls import path

from .views import * 

app_name = 'post'

urlpatterns = [
    path('', PostList.as_view(), name='blog'),
    #path('blog_single', blog_single, name='blog_single'),
    path('<slug:slug>/', PostDetail.as_view(), name='blog_single'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth import views as auth_views
from dashboard.views import ChangePasswordView
#from account.views import  as X
from account.views import  LoginPage
#LoginPage
from account import views as V
from dashboard import views as M


from django.conf.urls import handler404, handler500

from django.conf.urls.i18n import  i18n_patterns

#from account import views as A

urlpatterns = i18n_patterns(
   # path('', include('account.urls')),
    path('dashboard/', include('dashboard.urls', namespace = 'dashboard')),

    path('', include('website.urls')),
    path('blog/', include('post.urls', namespace = 'post')),

  #  path('dashboard/login/', V.login_view, name='login'),   

    path('dashboard/login/', LoginPage.as_view(), name='login'),   
    path("logout/", M.auth_logout, name="logout"),
    path('admin/', admin.site.urls),
   
    path('dashboard/password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)

#handler404 = 'website.views.handel404'
#handler500 = 'website.views.handel500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block body %}
   
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i> الصفحة الرئيسية للوحة تحكم الموقع </a>
        </div><!-- /.col -->
        
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <section class="content">
    <div class="container-fluid">

              <!-- Info boxes -->
              <div class="row">
                <div class="col-12 col-sm-6 col-md-3">
                  <div class="info-box">
                    <span class="info-box-icon bg-info elevation-1"><i class="fas fa-cog"></i></span>
      
                    <div class="info-box-content">
                      <span class="info-box-text">المستخدمين</span>
                      <span class="info-box-number">
                        10
                        <small>%</small>
                      </span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>
                <!-- /.col -->
                <div class="col-12 col-sm-6 col-md-3">
                  <div class="info-box mb-3">
                    <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-tag"></i></span>
      
                    <div class="info-box-content">
                      <span class="info-box-text">الاقسام</span>
                      <span class="info-box-number">41,410</span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>
                <!-- /.col -->
      
                <!-- fix for small devices only -->
                <div class="clearfix hidden-md-up"></div>
      
                <div class="col-12 col-sm-6 col-md-3">
                  <div class="info-box mb-3">
                    <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>
      
                    <div class="info-box-content">
                      <span class="info-box-text">التعليقات</span>
                      <span class="info-box-number">760</span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>
                <!-- /.col -->
                <div class="col-12 col-sm-6 col-md-3">
                  <div class="info-box mb-3">
                    <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>
      
                    <div class="info-box-content">
                      <span class="info-box-text">الصفحات</span>
                      <span class="info-box-number">2,000</span>
                    </div>
                    <!-- /.info-box-content -->
                  </div>
                  <!-- /.info-box -->
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
                      <!-- Info boxes -->
   
        <!-- /.row -->

      <h5 class="mb-2" >الوصول السريع</h5>
      <div class="row text-center">
        <!-- /.col -->      
        <div class="col-md-3 col-sm-3 col-6">
          <div class="info-box">
            <span class="info-box-icon bg-danger" style="width: 100%; background-color: #c0392b">
             <a href="">
              <h4>استعراض الموقع</h4>  
             </a>
            </span>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <div class="col-md-3 col-sm-3 col-6">
          <div class="info-box">
            <span class="info-box-icon bg-success" style="width: 100%;">
              <a href="{% url 'dashboard:informaion_site'  %}">
                <h4>تعديل البيانات الموقع</h4>
              </a>
            </span>
            <!-- /.info-box-content -->
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-6" style="text-align: center;">
          <div class="info-box">
            <span class="info-box-icon bg-warning" style="width: 100%;background-color: ">
              <a href="{% url 'dashboard:services_add'%}">
                <h4>إضافة قسم</h4>
              </a>
            </span>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <div class="col-md-3 col-sm-3 col-6">
          <div class="info-box">
            <span class="info-box-icon bg-info " style="width: 100%; background-color: #2c3e50">
              <a href="{% url 'dashboard:posts'  %}">
                <h4>إضافة مقال</h4>
              </a>
            </span>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
      </div>
      <!-- =========================================================== -->
      <h5 class="mt-4 mb-2">احصائيات عامة للموقع </h5>
      <!-- Small boxes (Stat box) -->
      <div class="row">
         <!-- ./col -->
         <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-warning">
            <div class="inner">
              <h3>{{project}}</h3>
              <p style="text-align: center; " class="">عدد الاقسام</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{% url 'dashboard:services' %}" class="small-box-footer"> عرض المزيد <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-info">
            <div class="inner">
              <h3>{{posts}}</h3>
              <p style="text-align: center;">عدد الصور</p>
            </div>
            <div class="icon">
              <i class="ion ion-bag"></i>
            </div>
            <a href="{% url 'dashboard:posts' %}" class="small-box-footer">  عرض المزيد  <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <!-- ./col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
  </section>


  <!-- /.content -->


</div>

{% endblock body %}