project/dashboard/urls.py
from django.urls import path, re_path
from . import views
from .views import (
    PageDeleteView,
    PageCreateView,
    AccountCreateView,
    AccountUpdateView,
    AccountDeleteView,
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostLanguageListView,
    PostLanguageCreateView,
    PostLanguageUpdateView,
    PostLanguageDeleteView,

    CommentListView
)

from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='home'),
    path('informaion_site/', views.edite_informaion, name='informaion_site'),
    path('profile/', views.profile, name='profile'),
    path("logout/", views.auth_logout, name="logout"),
###
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete', views.delete, name='delete'),

###
    path('service/', views.services, name='services'),
    path('service/edite/<int:id>/', views.services_edite, name='services_edite'),
    path('service/delete/<int:id>/', views.services_delete, name='services_delete'),
    path('service/create/', views.services_add, name='services_add'),


##
    path('page/', views.page, name='page'),
    path('page/about', views.page_about, name='page_about'),

    path('page/create/', PageCreateView.as_view(), name='page_add'),
    path('page/edite/<int:id>/', views.page_edite, name='page_edite'),
 #   path('page/delete/<int:id>/', views.page_delete, name='page_delete'),
    path('page/delete/<int:pk>/', PageDeleteView.as_view(), name='page_delete'),

##
    path('aluser/<int:pk>', views.AEditUser.as_view(), name='user_edite'),
    path('aluser/', views.user_show, name='accounts'),
   # path('create_use/', views.create_user, name='create_user_form'),
   
    path('account/create/', AccountCreateView.as_view(), name='accounts_create'),
    path('account/update/<int:pk>/', AccountUpdateView.as_view(), name='accounts_update'),
    path('account/delete/<int:pk>/', AccountDeleteView.as_view(), name='accounts_delete'),
    
    path('alvuser/<int:pk>', views.ALViewUser.as_view(), name='alvuser'),
   # path('aeuser/<int:pk>', views.AEditUser.as_view(), name='aeuser'),
   # path('aduser/<int:pk>', views.ADeleteUser.as_view(), name='aduser'),



    #### posts
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
  # path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    #path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),

    path('post/update/<int:id>/', views.post_update, name='post_update'),
    path('post/delete/<int:id>/', views.post_delete, name='post_delete'),

    path('posts/translation/', PostLanguageListView.as_view(), name='posts_language'),
    path('post/add/translation/<int:id>/', PostLanguageCreateView.as_view(), name='post_language_create'),
    path('post/update/translation/<int:pk>/', views.post_language_update, name='post_language_update'),
    path('post/delete/translation/<int:pk>/', views.post_language_delete, name='post_language_delete'),

        # Comments Urls
    path('comment/', CommentListView.as_view(), name='comments'),
    path('comments/delete/<int:id>/', views.comment_delete, name='comment_delete'),



###  brands
    path('brands/', views.brands, name='brands'),
    path('brands/delete/<int:id>/', views.brands_delete, name='brands_delete'),
    path('brands/create/', views.brands_add, name='brands_add'),

    
]

project/post/urls.py
from django.urls import path

from .views import * 

app_name = 'post'

urlpatterns = [
    path('', PostList.as_view(), name='blog'),
    #path('blog_single', blog_single, name='blog_single'),
    path('<slug:slug>/', PostDetail.as_view(), name='blog_single'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth import views as auth_views
from dashboard.views import ChangePasswordView
#from account.views import  as X
from account.views import  LoginPage
#LoginPage
from account import views as V
from dashboard import views as M


from django.conf.urls import handler404, handler500

from django.conf.urls.i18n import  i18n_patterns

#from account import views as A

urlpatterns = i18n_patterns(
   # path('', include('account.urls')),
    path('dashboard/', include('dashboard.urls', namespace = 'dashboard')),

    path('', include('website.urls')),
    path('blog/', include('post.urls', namespace = 'post')),

  #  path('dashboard/login/', V.login_view, name='login'),   

    path('dashboard/login/', LoginPage.as_view(), name='login'),   
    path("logout/", M.auth_logout, name="logout"),
    path('admin/', admin.site.urls),
   
    path('dashboard/password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)

#handler404 = 'website.views.handel404'
#handler500 = 'website.views.handel500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/website/urls.py
from django.urls import path

from . import views 
app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('project/', views.project, name='project'),

]

project/templates/includes/footer.html
<footer class="main-footer">
  <strong> &copy; 2022-2025 <a href="#">جميع الحقوق محفوظة</a></strong>
</footer>

project/templates/includes/navigation.html
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load static %}
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        
        <a href="{% url 'dashboard:home' %}" class="nav-link"><i class=" fas fa-home"></i>   </a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        
       
        <a href="{% url 'website:index' %}" class="nav-link">
          <i class="fas fa-desktop"></i> <strong> {% trans 'views' %} </strong> 
        </a>
      </li>

    </ul>
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto-navbav">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <img src="{{ user.profile.image.url }}" alt="" class="img-size-50 mr-3 img-circle" style="width: 30px;">
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">{% trans 'settings' %} </span>
          
          <div class="dropdown-divider"></div>
          <a href="{% url 'website:index' %} " class="dropdown-item">
            <i class="fas fa-desktop mr-2"></i> {% trans 'views' %} 
          </a>

          <div class="dropdown-divider"></div>
          <a href="{% url 'dashboard:profile' %}" class="dropdown-item">
            <i class="fas fa-user mr-2"></i> {% trans 'profile' %} 
          </a>

          <div class="dropdown-divider"></div>
          <a href="{% url 'password_change' %}" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> {% trans 'change password' %} 
          </a>
         
          
          <div class="dropdown-divider"></div>
              <a class="dropdown-item" style=" font-size: large;" href="{% url 'logout' %}" role="button">
                <i class="fas fa-sign-out-alt"></i> {% trans 'logout' %} </a>
          
            

          
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>

      <li class="nav-item dropdown">

        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}


        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fas fa-language"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
          <span class="dropdown-item dropdown-header"><a href="/{{lan.code}}{{request.path|slice:'3:'}}">{{lan.name_local}}</a></span>
          {% for lan in languages %}
          {% if lan.code !=  LANGUAGE_CODE %}

          <span class="dropdown-item dropdown-header"><a href="/{{lan.code}}{{request.path|slice:'3:'}}">{{lan.name_local}}</a></span>

        
          {% endif %}
          {% endfor %}
        </div>
      </li>
     
    </ul>
  </nav>
  <!-- /.navbar -->

project/templates/includes/nns.html
{% load static %}

<!--  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/overlayscrollbars/2.3.0/browser/overlayscrollbars.browser.es6.min.js" integrity="sha512-tu2VesH7qQi/IX4MN47Zw0SCia4hgBgu4xY/fP/gV2XcqdZsIh1B5wbSy4Mk5AhkkfTj/XMDQt86wzsZIsxPSA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Filterizr-->
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js"></script>
<!-- jQuery 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 Bootstrap 4 -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
 <!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js" integrity="sha512-X/YkDZyjTf4wyc2Vy16YGCPHwAY8rZJY+POgokZjQB2mhIRFJCckEGc6YyX9eNsPfn0PzThEuNs+uaomE5CO6A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- AdminLTE App -->
<script src="{% static 'assets/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'assets/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'assets/dist/js/demo.js' %}"></script>

<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>


<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>

project/templates/includes/scripts.html
 {% load static %}

<!--  -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/overlayscrollbars/2.3.0/browser/overlayscrollbars.browser.es6.min.js" integrity="sha512-tu2VesH7qQi/IX4MN47Zw0SCia4hgBgu4xY/fP/gV2XcqdZsIh1B5wbSy4Mk5AhkkfTj/XMDQt86wzsZIsxPSA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Filterizr-->
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js"></script>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
 <!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>

<!-- AdminLTE App -->
<script src="{% static 'assets/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'assets/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'assets/dist/js/demo.js' %}"></script>
<!-- Slick Carousel -->
<script src="{% static 'assets/plugins/slick/slick.min.js' %}"></script>
<script src="{% static 'assets/plugins/slick/slick-animation.min.js' %}"></script>
<!-- Color box -->
<script src="{% static 'assets/plugins/colorbox/jquery.colorbox.js' %}"></script>
<!-- shuffle -->
<script src="{% static 'assets/plugins/shuffle/shuffle.min.js' %}" defer></script>
<script src="{% static 'assets/plugins/jquery.filterizr.min.js' %}"></script>

<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>



<script src="{% static 'assets\plugins\bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets\plugins\jquery.min.js' %}"></script>
<script src="{% static 'assets\plugins\bootstrap\bootstrap.min.js' %}"></script>

project/templates/includes/sidenav.html
{% load i18n %}

{% load static %}

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'dashboard:profile' %}" class="brand-link">
      <img src="{{ user.profile.image.url }}" alt="" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">{{user.username}}</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item has-treeview">
            <a href="{% url 'dashboard:home' %}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>    {% trans 'dashboard' %} </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="{% url 'dashboard:informaion_site'  %}" class="nav-link">
              <i class="nav-icon fas fa-cog fa-fw"></i>
              <p>{% trans 'site settings' %}  </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="{% url 'dashboard:services' %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                <i class="right fas fa-angle-left"></i>
                   {% trans 'tags' %} 
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'dashboard:services' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p> {% trans 'services' %}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:services' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p> {% trans 'trans brands' %}</p>
                </a>
              </li>
              
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="{% url 'dashboard:posts' %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                <i class="right fas fa-angle-left"></i>
                   {% trans 'articles' %} 
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'dashboard:posts' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p> {% trans 'articles' %}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:posts_language' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p> {% trans 'translation articles' %}</p>
                </a>
              </li>
              
            </ul>
          </li>

          <li class="nav-item">
            <a href="{% url 'dashboard:brands'  %}" class="nav-link">
              <i class="far fa-circle nav-icon"></i>
              <p> {% trans 'brands' %}</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'dashboard:accounts'  %}" class="nav-link">
              <i class=" nav-icon fas fa-users"></i>
              <p> {% trans 'users' %} </p>
            </a>
          </li>


          <li class="nav-item">
            <a href="{% url 'dashboard:gallery' %}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                  {% trans 'images' %} 
              </p>
            </a>
          </li> 
          <li class="nav-item has-treeview menu--open">
            <a href="#" class="nav-link ">

              <i class="nav-icon fas fa-book"></i>
              <p>
                 {% trans 'pages' %} 
                <i class="right fas fa-angle-left"></i>

                </p>
              
            
            </a>
            <ul class="nav nav-treeview">
            
              <li class="nav-item">
                <a href="{% url 'dashboard:page' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>   {% trans 'home' %} </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:page_about' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>  {% trans 'about' %} </p>
                </a>
              </li>
              
            </ul>
         </li>      
         <li class="nav-item">
          <a href="{% url 'dashboard:comments'  %}" class="nav-link">
            <i class=" nav-icon fas fa-comments"></i>
            <p> {% trans 'comments' %} </p>
          </a>
        </li>

          <li class="nav-item has-treeview">
            <a href="{% url 'logout' %}" class="nav-link">
              <i class="fas fa-sign-out-alt"></i> 
              <p>
                  {% trans 'logout' %}
              </p>
            </a>
          </li>  
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

project/templates/includes/style.html
{% load static %} 
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/d6a07002fc.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

 <!-- Sakhr
 Tempusdominus Bbootstrap 4 -->
 
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
 
  <!-- Font Awesome -->
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'assets/dist/css/adminlte.min.css' %}">
  <!-- summernote -->
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- SweetAlert2 -->
  <link rel="stylesheet" href="{% static 'assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.css"/>

   <!-- slick Carousel -->
 <link rel="stylesheet" href="{% static 'assets/plugins/slick/slick.css' %}">
 <link rel="stylesheet" href="{% static 'assets/plugins/slick/slick-theme.css' %}">
 <!-- Colorbox -->
 <link rel="stylesheet" href="{% static 'assets/plugins/colorbox/colorbox.css' %}">