project/dashboard/urls.py
from django.urls import path, re_path
from . import views
from .views import (
    PageDeleteView,
    PageCreateView,
    AccountCreateView,
    AccountUpdateView,
    AccountDeleteView,
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostLanguageListView,
    PostLanguageCreateView,
    PostLanguageUpdateView,
    PostLanguageDeleteView,

    CommentListView
)

from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='home'),
    path('informaion_site/', views.edite_informaion, name='informaion_site'),
    path('profile/', views.profile, name='profile'),
    path("logout/", views.auth_logout, name="logout"),
###
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete', views.delete, name='delete'),

###
    path('service/', views.services, name='services'),
    path('service/edite/<int:id>/', views.services_edite, name='services_edite'),
    path('service/delete/<int:id>/', views.services_delete, name='services_delete'),
    path('service/create/', views.services_add, name='services_add'),


##
    path('page/', views.page, name='page'),
    path('page/about', views.page_about, name='page_about'),

    path('page/create/', PageCreateView.as_view(), name='page_add'),
    path('page/edite/<int:id>/', views.page_edite, name='page_edite'),
 #   path('page/delete/<int:id>/', views.page_delete, name='page_delete'),
    path('page/delete/<int:pk>/', PageDeleteView.as_view(), name='page_delete'),

##
    path('aluser/<int:pk>', views.AEditUser.as_view(), name='user_edite'),
    path('aluser/', views.user_show, name='accounts'),
   # path('create_use/', views.create_user, name='create_user_form'),
   
    path('account/create/', AccountCreateView.as_view(), name='accounts_create'),
    path('account/update/<int:pk>/', AccountUpdateView.as_view(), name='accounts_update'),
    path('account/delete/<int:pk>/', AccountDeleteView.as_view(), name='accounts_delete'),
    
    path('alvuser/<int:pk>', views.ALViewUser.as_view(), name='alvuser'),
   # path('aeuser/<int:pk>', views.AEditUser.as_view(), name='aeuser'),
   # path('aduser/<int:pk>', views.ADeleteUser.as_view(), name='aduser'),



    #### posts
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
  # path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    #path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),

    path('post/update/<int:id>/', views.post_update, name='post_update'),
    path('post/delete/<int:id>/', views.post_delete, name='post_delete'),

    path('posts/translation/', PostLanguageListView.as_view(), name='posts_language'),
    path('post/add/translation/<int:id>/', PostLanguageCreateView.as_view(), name='post_language_create'),
    path('post/update/translation/<int:pk>/', views.post_language_update, name='post_language_update'),
    path('post/delete/translation/<int:pk>/', views.post_language_delete, name='post_language_delete'),

        # Comments Urls
    path('comment/', CommentListView.as_view(), name='comments'),
    path('comments/delete/<int:id>/', views.comment_delete, name='comment_delete'),



###  brands
    path('brands/', views.brands, name='brands'),
    path('brands/delete/<int:id>/', views.brands_delete, name='brands_delete'),
    path('brands/create/', views.brands_add, name='brands_add'),

    
]

project/post/urls.py
from django.urls import path

from .views import * 

app_name = 'post'

urlpatterns = [
    path('', PostList.as_view(), name='blog'),
    #path('blog_single', blog_single, name='blog_single'),
    path('<slug:slug>/', PostDetail.as_view(), name='blog_single'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth import views as auth_views
from dashboard.views import ChangePasswordView
#from account.views import  as X
from account.views import  LoginPage
#LoginPage
from account import views as V
from dashboard import views as M


from django.conf.urls import handler404, handler500

from django.conf.urls.i18n import  i18n_patterns

#from account import views as A

urlpatterns = i18n_patterns(
   # path('', include('account.urls')),
    path('dashboard/', include('dashboard.urls', namespace = 'dashboard')),

    path('', include('website.urls')),
    path('blog/', include('post.urls', namespace = 'post')),

  #  path('dashboard/login/', V.login_view, name='login'),   

    path('dashboard/login/', LoginPage.as_view(), name='login'),   
    path("logout/", M.auth_logout, name="logout"),
    path('admin/', admin.site.urls),
   
    path('dashboard/password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)

#handler404 = 'website.views.handel404'
#handler500 = 'website.views.handel500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/post/forms.py
from django import forms
from .models import Comment

 

class CommentForm(forms.ModelForm):
    user_comment = forms.CharField(
        label="العنوان",
        widget=forms.TextInput(
            attrs={
            }
        )
    )
    email = forms.EmailField(
        required=True,
        label="البريد",

        widget=forms.EmailInput()
    )
    content  = forms.CharField(
        label="الرسالة",
        widget=forms.Textarea(),
        required=True
    )

    class Meta:
        model = Comment
        fields = ['email' ,'user_comment','content']

project/dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django import template
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import *
from django.contrib import auth, messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator

from post.models import *
from .decorators import admin_and_editor_only, admin_only



from django.shortcuts import render, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView, View
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

#@method_decorator(admin_and_editor_only, name='dispatch')
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'dashboard/post/post_list.html'
    context_object_name = 'posts'

#@method_decorator(admin_and_editor_only, name='dispatch')
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'dashboard/post/post_form.html'
    form_class = PostForm
    post_slug = None

    def form_valid(self, form):
        form_2 = form.save(commit=False)
        form_2.author = self.request.user
        form_2.save()
        self.post_slug = form_2.slug
        messages.success(self.request, f'"{form.instance.title}" has been created successfully')
            
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('dashboard:post')


@user_passes_test(lambda u: u.is_superuser)
def post_update(request, id ):
    formm = Post.objects.get(id=id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=formm)
        if form.is_valid():
            form.save()
            messages.success(request, f' لقد تم حفظ التعديل بنجاح')
            return HttpResponseRedirect('/dashboard/category')
    else:
        form = PostForm(instance=formm)
    context={
        'form':form,
    }
    return render(request, 'dashboard/post/post_form.html', context)
##

def post_delete(request, id):
    category = Post.objects.get(id=id)
    category.delete()
    messages.success(request, f"  تم الحذف بنجاح")
    return redirect(reverse('dashboard:posts'))



# Comments Views

@method_decorator(admin_and_editor_only, name='dispatch')
class CommentListView(LoginRequiredMixin, ListView):
    model = Comment
    template_name = 'dashboard/comment_list.html'
    context_object_name = 'comments'
 
def comment_delete(request, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    messages.success(request, f"  تم الحذف بنجاح")
    return redirect(reverse('dashboard:comments'))


#@method_decorator(admin_and_editor_only, name='dispatch')
class PostLanguageListView(LoginRequiredMixin, ListView):
    model = PostLanguage
    template_name = 'dashboard/post/posts_lang_lish.html'
    context_object_name = 'posts'

#@method_decorator(admin_and_editor_only, name='dispatch')
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'dashboard/confirm_delete.html'
    success_url = reverse_lazy('dashboard:posts')     
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, f'"{self.get_object()}" has been deleted successfully')
        return super().delete(request, *args, **kwargs)

#@method_decorator(admin_and_editor_only, name='dispatch')
class PostLanguageCreateView(LoginRequiredMixin, CreateView):
    model = PostLanguage
    template_name = 'dashboard/post/post_form.html'
    form_class = PostLanguageForm
    success_url = reverse_lazy('dashboard:posts')
    post_slug = None

    def get_form(self):
        form = PostLanguageForm(initial={'post':self.kwargs.get('id'), 'language':'1'})
        
        if self.request.method == 'POST':
            form = PostLanguageForm(self.request.POST)
    
        return form

        
    def form_valid(self, form):
        messages.success(self.request, f'"{form.instance.title}" has been created successfully')
        return super().form_valid(form)

#@method_decorator(admin_and_editor_only, name='dispatch')
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'dashboard/post_form.html'
    form_class = PostForm
    post_slug = None
    
    def test_func(self):
        return self.request.user.is_superuser or self.get_object().author == self.request.user
    
    def form_valid(self, form):
        messages.success(self.request, f'"{form.instance.title}" has been updated successfully')
        post = form.save()
        self.post_slug = post.slug
        return super().form_valid(form)    
    
        
    def get_success_url(self):
        return reverse('post:blog', kwargs={'slug':self.post_slug})    



#@method_decorator(admin_and_editor_only, name='dispatch')
class PostLanguageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = PostLanguage
    template_name = 'dashboard/post_form.html'
    form_class = PostLanguageForm
    post_slug = None
    
    def test_func(self):
        return self.request.user.is_superuser or self.get_object().post.author == self.request.user
    
    def form_valid(self, form):
        messages.success(self.request, f'"{form.instance.title}" has been updated successfully')
        post = form.save()
        self.post_slug = post.post.slug
        return super().form_valid(form)    
        
    def get_success_url(self):
        return reverse('post:post', kwargs={'slug':self.post_slug})    

#@method_decorator(admin_and_editor_only, name='dispatch')
class PostLanguageDeleteView(LoginRequiredMixin, DeleteView):
    model = PostLanguage
    template_name = 'dashboard/confirm_delete.html'
    success_url = reverse_lazy('dashboard:posts')     
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, f'"{self.get_object()}" has been deleted successfully')
        return super().delete(request, *args, **kwargs)



@user_passes_test(lambda u: u.is_superuser)
def post_language_update(request, pk ):
    formm = PostLanguage.objects.get(id=pk)
    if request.method == "POST":
        form = PostLanguageForm(request.POST, request.FILES, instance=formm)
        if form.is_valid():
            form.save()
            messages.success(request, f' لقد تم حفظ التعديل بنجاح')
            return HttpResponseRedirect('/dashboard/translation')
    else:
        form = PostLanguageForm(instance=formm)
    context={
        'form':form,
    }
    return render(request, 'dashboard/post/post_form.html', context)
##

def post_language_delete(request, pk):
    category = Post.objects.get(id=pk)
    category.delete()
    messages.success(request, f"  تم الحذف بنجاح")
    return redirect(reverse('dashboard:posts_language'))




#@method_decorator(admin_and_editor_only, name='dispatch')
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'dashboard/confirm_delete.html'
    success_url = reverse_lazy('dashboard:posts')     
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, f'"{self.get_object()}" has been deleted successfully')
        return super().delete(request, *args, **kwargs)


####### brands ######
#@method_decorator(admin_and_editor_only, name='dispatch')
def brands(request):
    brands = Brands.objects.all()
    ##
    context = {'brands':brands}
    return render(request, 'dashboard/brands/brands.html', context)
####
#
def brands_add(request):
    if request.method == "POST":
        form = BrandsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f' لقد تم حفظ التعديل بنجاح')

            return HttpResponseRedirect('/dashboard/brands')
    else:
        form = BrandsForm()
    context={
        'form':form,

    }
    return render(request, 'dashboard/brands/brands_add.html', context)
#
def brands_delete(request, id):
    category = Brands.objects.get(id=id)
    category.delete()
    messages.success(request, f"  تم الحذف بنجاح")
    return redirect(reverse('dashboard:brands'))


    


def is_superuser(user):
    return user.is_superuser

### home ##
def index(request):
    services = Services.objects.all().count()
    post = Post.objects.all().count()
    if request.user.is_authenticated:
        user = request.user.username #.id
        context = {'services':services,'post':post}
        return render(request, 'index.html', context)
    else:
        return HttpResponseRedirect('/dashboard/login')

####### category ######
#@method_decorator(admin_and_editor_only, name='dispatch')
def services(request):
    services = Services.objects.all()
    ##
    context = {'services':services}
    return render(request, 'dashboard/services/services.html', context)
####
#
def services_add(request):
    #formm = Category.objects.get(id=id)
    if request.method == "POST":
        form = ServicesForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f' لقد تم حفظ التعديل بنجاح')

project/dashboard/templates/dashboard/post/post_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} تعديل {% endblock %}
{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content">
        <div class="container-fluid">
          <div class="row ">
            <div class="col-md-12" style="margin-top: 10px;">
                <ol class="breadcrumb ">
                  <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i>الصفحة الرئيسية</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'dashboard:posts' %}">الخدمات</a></li>
                  <li class="breadcrumb-item active">اضافة</li>
                </ol>

                  {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    {{ message }}
                </div>
                  {% endfor %}
                <div class="card ">
                    <div class="card-header">
                        <div class="card-tools">
                          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                              <i class="fas fa-minus"></i>
                          </button>
                        </div>
                    </div>
                    <div class="card-body">
                      <form action="" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                              <div class="row">
                                  <div class="col-md-12">
                                    <div class="form-group">
                                        {{form|crispy}}
                                        {{form.media}}
                                    </div>
                                  </div>  
                                  <div class="col-12">
                                      <button type="submit" class="btn btn-primary btn-block">حفظ التغير </button>
                                  </div>
                              </div>
                      </form>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock body %}

project/dashboard/templates/dashboard/post/post_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% block title %} المشاريع{% endblock %}

{% block body %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md-12 ">
            <div class=" " style="margin-top: 10px;" > 
              <ol class="breadcrumb ">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i>الصفحة الرئيسية</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'dashboard:posts' %}">المشاريع</a></li>
              </ol>          
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                  {{ message }}
              </div>
            {% endfor %}
      <!-- Default bopost -->
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title"></h3>
                  <div class="card-tools">
                    <a href="{% url 'dashboard:post_create'%} " class="btn btn-success pull-left "><i class="fa fa-plus"></i>اضافة</a>
                  </div>
                </div>
                <div class="card-body p-0 " >
                  <div class="table-responsive">

                  <table class="table table-striped projects" style="overflow: auto; " id="dataTable" width="100%" cellspacing="0">
                      <thead>
                          <tr>

                            <th>{% trans 'title' %}</th>
                            <th>{% trans 'image' %}</th>
                            <th>{% trans 'languages' %}</th>
                            <th>{% trans 'views' %}</th>
                            <th>{% trans 'published at' %}</th>
                            <th>{% trans 'add translate' %}</th>
                            <th>{% trans 'stat' %}</th>
                            <th>{% trans 'edite' %}</th>
                            <th>{% trans 'delete' %}</th>
                        

                             
                          </tr>
                      </thead>
                      <tbody>
                        {% for post in posts %}
                          <tr>
                              
                              <td>
                                    <a href="">
                                        {{post.title|slice:'6'}}
                                        {% if post.title|length > 6 %}
                                        ...
                                        {% endif %}
                                    </a>                             
                              </td>

                              <td>
                                  <ul class="list-inline">
                                      <li class="list-inline-item">
                                          <img alt="Avatar" class="table-avatar" src="{{ post.image.url }}">
                                      </li>
                                  </ul>
                              </td>
                              <td>
                                <a href="">{{post.language}}</a>
                                {% for post_lan in post.post_lang.all %}
                                    , <a href="/{{post_lan.language}}/{{post.slug}}">{{post_lan.language}}</a>
                                {% endfor %}
                            </td>						
                            <td>{{post.views_count}}</td>
                            <td>{{post.published_at|date:'d M Y'}}</td>
                            <td><a href="{% url 'dashboard:post_language_create' post.id %}" class="btn btn-sm info">{% trans 'Add Translate' %}</a></td>

                            {% if post.active %}
                            <td><div class="btn btn-sm info">{% trans 'Active' %}</div></td>
                            {% else %}
                            <td><div class="btn btn-sm warning">{% trans 'Inactive' %}</div></td>
                            {% endif %}
                                    
                            
                              <td class="project-actions tepostt-center">
                                  <a href="{% url 'dashboard:post_update' post.id %}">
                                    <i class="fas fa-edit"></i> 
                                  </a>

                                  
                              </td>
                              <td class="project-actions tepostt-center">
                                <a href="{% url 'dashboard:post_delete' post.id %}">
                                    <i class="fas fa-trash"></i>
                                  </a>
                              </td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
                  </div>
                </div>
                <!-- /.card-body -->
              </div>
          </div>
        </div>
      </div>
      </div>
            <!-- /.حذف -->
      <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">هل أنت متأكد؟</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% for post in posts %}
            <div class="modal-body">
              <p>أأنت متأكد أنك تريد حذف العنصر المحدد؟ جميع العناصر المرتبطة بها سيتم حذفها:&hellip;</p>
            </div>
            <div class="modal-footer justify-content-between">
              <a class="delete" href="{% url 'dashboard:post_delete' post.id %}" >
              <button type="button" class="btn btn-primary">نعم أنا متأكد</button>
              </a>
              {% endfor %}
              <button type="button" class="btn btn-default" data-dismiss="modal"> لا ترجوع للخلف</button>
            
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.card -->
  </section>
    <!-- /.content -->
  </div>
{% endblock %}

project/dashboard/templates/dashboard/post/posts_lang_lish.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% block title %} {% trans 'posts list' %}{% endblock %}

{% block body %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md-12 ">
            <div class=" " style="margin-top: 10px;" > 
              <ol class="breadcrumb ">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i>الصفحة الرئيسية</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'dashboard:posts_language' %}">المشاريع</a></li>
              </ol>          
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                  {{ message }}
              </div>
            {% endfor %}
      <!-- Default bopost -->
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title"></h3>
                  <div class="card-tools">
                    <a href="{% url 'dashboard:post_create'%} " class="btn btn-success pull-left "><i class="fa fa-plus"></i>اضافة</a>
                  </div>
                </div>
                <div class="card-body p-0 " >
                  <table class="table table-striped projects" style="overflow: auto;">
                      <thead>
                          <tr>

                           

                            <th>{% trans 'title' %}</th>
                            <th>{% trans 'languages' %}</th>
                            <th>{% trans 'state' %}</th>
                            <th>{% trans 'delete' %}</th>
                            <th>{% trans 'update' %}</th>
                        

                             
                          </tr>
                      </thead>
                      <tbody>
                        {% for post in posts %}
                          <tr>
                              
                              <td>
                                    <a href="">
                                        {{post.title|slice:'6'}}
                                        {% if post.title|length > 6 %}
                                        ...
                                        {% endif %}
                                    </a>                             
                              </td>

                         
                              <td>
                                <a href="">{{post.language}}</a>
                                {% for post_lan in post.post_lang.all %}
                                    , <a href="/{{post_lan.language}}/{{post.slug}}">{{post_lan.language}}</a>
                                {% endfor %}
                            </td>						

                            {% if post.active %}
                            <td><div class="btn btn-sm info">{% trans 'Active' %}</div></td>
                            {% else %}
                            <td><div class="btn btn-sm warning">{% trans 'Inactive' %}</div></td>
                            {% endif %}
                                    
                            
                              <td class="project-actions tepostt-center">
                                  <a href="{% url 'dashboard:post_language_update' post.pk %}">
                                    <i class="fas fa-edit"></i> 
                                  </a>

                                  
                              </td>
                              <td class="project-actions tepostt-center">
                                <a href="{% url 'dashboard:post_language_delete' post.pk %}">
                                    <i class="fas fa-trash"></i>
                                  </a>
                              </td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
          </div>
        </div>
      </div>
      </div>
            <!-- /.حذف -->
      <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">هل أنت متأكد؟</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% for post in posts %}
            <div class="modal-body">
              <p>أأنت متأكد أنك تريد حذف العنصر المحدد؟ جميع العناصر المرتبطة بها سيتم حذفها:&hellip;</p>
            </div>
            <div class="modal-footer justify-content-between">
              <a class="delete" href="{% url 'dashboard:post_delete' post.id %}" >
              <button type="button" class="btn btn-primary">نعم أنا متأكد</button>
              </a>
              {% endfor %}
              <button type="button" class="btn btn-default" data-dismiss="modal"> لا ترجوع للخلف</button>
            
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.card -->
  </section>
    <!-- /.content -->
  </div>
{% endblock %}