project/dashboard/urls.py
from django.urls import path, re_path
from . import views
from .views import (
    PageDeleteView,
    PageCreateView,
    AccountCreateView,
    AccountUpdateView,
    AccountDeleteView,
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostLanguageListView,
    PostLanguageCreateView,
    PostLanguageUpdateView,
    PostLanguageDeleteView,

    CommentListView
)

from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='home'),
    path('informaion_site/', views.edite_informaion, name='informaion_site'),
    path('profile/', views.profile, name='profile'),
    path("logout/", views.auth_logout, name="logout"),
###
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete', views.delete, name='delete'),

###
    path('service/', views.services, name='services'),
    path('service/edite/<int:id>/', views.services_edite, name='services_edite'),
    path('service/delete/<int:id>/', views.services_delete, name='services_delete'),
    path('service/create/', views.services_add, name='services_add'),


##
    path('page/', views.page, name='page'),
    path('page/about', views.page_about, name='page_about'),

    path('page/create/', PageCreateView.as_view(), name='page_add'),
    path('page/edite/<int:id>/', views.page_edite, name='page_edite'),
 #   path('page/delete/<int:id>/', views.page_delete, name='page_delete'),
    path('page/delete/<int:pk>/', PageDeleteView.as_view(), name='page_delete'),

##
    path('aluser/<int:pk>', views.AEditUser.as_view(), name='user_edite'),
    path('aluser/', views.user_show, name='accounts'),
   # path('create_use/', views.create_user, name='create_user_form'),
   
    path('account/create/', AccountCreateView.as_view(), name='accounts_create'),
    path('account/update/<int:pk>/', AccountUpdateView.as_view(), name='accounts_update'),
    path('account/delete/<int:pk>/', AccountDeleteView.as_view(), name='accounts_delete'),
    
    path('alvuser/<int:pk>', views.ALViewUser.as_view(), name='alvuser'),
   # path('aeuser/<int:pk>', views.AEditUser.as_view(), name='aeuser'),
   # path('aduser/<int:pk>', views.ADeleteUser.as_view(), name='aduser'),



    #### posts
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
  # path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    #path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),

    path('post/update/<int:id>/', views.post_update, name='post_update'),
    path('post/delete/<int:id>/', views.post_delete, name='post_delete'),

    path('posts/translation/', PostLanguageListView.as_view(), name='posts_language'),
    path('post/add/translation/<int:id>/', PostLanguageCreateView.as_view(), name='post_language_create'),
    path('post/update/translation/<int:pk>/', views.post_language_update, name='post_language_update'),
    path('post/delete/translation/<int:pk>/', views.post_language_delete, name='post_language_delete'),

        # Comments Urls
    path('comment/', CommentListView.as_view(), name='comments'),
    path('comments/delete/<int:id>/', views.comment_delete, name='comment_delete'),



###  brands
    path('brands/', views.brands, name='brands'),
    path('brands/delete/<int:id>/', views.brands_delete, name='brands_delete'),
    path('brands/create/', views.brands_add, name='brands_add'),

    
]

project/post/urls.py
from django.urls import path

from .views import * 

app_name = 'post'

urlpatterns = [
    path('', PostList.as_view(), name='blog'),
    #path('blog_single', blog_single, name='blog_single'),
    path('<slug:slug>/', PostDetail.as_view(), name='blog_single'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.auth import views as auth_views
from dashboard.views import ChangePasswordView
#from account.views import  as X
from account.views import  LoginPage
#LoginPage
from account import views as V
from dashboard import views as M


from django.conf.urls import handler404, handler500

from django.conf.urls.i18n import  i18n_patterns

#from account import views as A

urlpatterns = i18n_patterns(
   # path('', include('account.urls')),
    path('dashboard/', include('dashboard.urls', namespace = 'dashboard')),

    path('', include('website.urls')),
    path('blog/', include('post.urls', namespace = 'post')),

  #  path('dashboard/login/', V.login_view, name='login'),   

    path('dashboard/login/', LoginPage.as_view(), name='login'),   
    path("logout/", M.auth_logout, name="logout"),
    path('admin/', admin.site.urls),
   
    path('dashboard/password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)

#handler404 = 'website.views.handel404'
#handler500 = 'website.views.handel500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language



from .decorators import get_or_create_editor_admin_group


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_images')
   
    @property    
    def is_admin(self):        
        _ , admin_group = get_or_create_editor_admin_group()
        
        if self.user.is_superuser:
            return True

        elif self.user.groups.exists():
            if admin_group in self.user.groups.all():
                return True

        return False
    
    @property    
    def is_admin_or_editor(self):        
        editors_group , admin_group = get_or_create_editor_admin_group()
        
        if self.user.is_superuser:
            return True

        elif self.user.groups.exists():
            groups = self.user.groups.all()
            if admin_group in groups or editors_group in groups:
                return True

        return False
        
    def __str__(self):
        try:
            return self.user.username
        except:
     
            return "none"
            
    
    
    def save(self, *args, **kwargs):
        """
            Overwrite save mehtod to rename a image and resize a big image
        """
        
        # Handle problem in upload_image function  (pk not generator yet)
        if self.pk is None:
            image = self.picture
            self.picture = None
            super().save(*args, **kwargs)
            self.picture = image

        super().save(*args, **kwargs)
        
        # image resize
        img = Image.open(self.picture.path)   
        if img.width > 400 or img.height > 400:
            img.thumbnail( (400, 400) )
            img.save(self.picture.path)
            
        
    def __str__(self):
        return self.user.username
##
def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "category/images/%s.%s"%(instance.id,extension)
##
class InformaionSite(models.Model):
    name_ar = models.CharField(_('name arabic'),max_length=60 , default='name')
    name_en = models.CharField(_('name english'),max_length=60 , default='name')

    description_ar = models.TextField(_('description arabic'),null=True, blank=True)
    description_en = models.TextField(_('description english'),null=True, blank=True)

    logo_white = models.ImageField(_('logo white'),upload_to='logo/', null=True, blank=True)
    logo_black = models.ImageField(_('logo icon black'),upload_to='logo/', null=True, blank=True)
    background_image = models.ImageField(_('background image'),upload_to='logo/', null=True, blank=True)
   
   # title_name =  models.CharField(_('title_name'),max_length=150)
    address = models.CharField(_('address'),max_length=60)
    email = models.EmailField(_('email'),null=True, blank=True)
    mobile = models.IntegerField(_('telephone'),null=True, blank=True)
    facebook = models.URLField(_('facebook'),null=True, blank=True)
    twitter = models.URLField(_('twitter'),null=True, blank=True)
    instagram = models.URLField(_('instagram'),null=True, blank=True)
    whatsapp = models.URLField(_('whatsapp'),null=True, blank=True)
    maps = models.CharField(_('maps'),max_length=200, null=True, blank=True)
    pubilished_at = models.DateTimeField(_('pubilished_at'),auto_now=True)

#    count_custemor = models.IntegerField(_('count_custemor'),)



##

def arabic_slugify(str):
    str = str.replace(" ", "-")
    str = str.replace(",", "-")
    str = str.replace("(", "-")
    str = str.replace(")", "")
    str = str.replace("?", "")
    return str
##
'''

class Post(models.Model):
    user = models.ForeignKey(User, related_name='user_blogs', on_delete=models.CASCADE)
    title  = models.CharField(max_length=60 ,blank=True, null=True)
    image = models.ImageField(upload_to='post/', null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    create_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=60,unique=True, allow_unicode=True, blank=True, null=True)

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            if not self.slug:
                self.slug = arabic_slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
'''

##
class Category(models.Model):
    name = models.CharField(max_length=30, blank=False, null=False)

    image = models.ImageField(upload_to='category/', null=False, blank=False)
    description = models.TextField(null=True, blank=False)
    create_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=60,unique=True, allow_unicode=True, blank=True, null=True)

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            if not self.slug:
                self.slug = arabic_slugify(self.name)
        super(Category, self).save(*args, **kwargs)



    def __str__(self):
        return self.name
##
class Project(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='category')
    name = models.CharField(max_length=60 ,blank=False, null=True)
    image = models.ImageField(upload_to='category/', null=False, blank=False)
    location  = models.CharField(max_length=60 ,blank=True, null=True)
    description = models.TextField(null=True, blank=False)
    create_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=60,unique=True, allow_unicode=True, blank=True, null=True)

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            if not self.slug:
                self.slug = arabic_slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
##
class Image(models.Model):
    image = models.ImageField(_('image'),upload_to=image_upload)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='project')
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category
    @property

    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
##
class Pages(models.Model):
    title  = models.CharField(max_length=60, blank=False)
    image = models.ImageField(upload_to='home/', null=False, blank=False)
    description = models.TextField(null=True, blank=False)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class PageAbout(models.Model):
    title_head  = models.CharField(max_length=60, null=False, blank=False)
    title_goal  = models.CharField(max_length=60, null=False, blank=False)
    description = models.TextField(null=True, blank=False)

   # image = models.ImageField(upload_to='services/', null=False, blank=False)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title_head









from post.models import Language


active_field_choices = [
    (True, _('Active')),
    (False, _('Inactive'))
]

##
class Services(models.Model):
    title  = models.CharField(max_length=60, null=False, blank=False)
    image = models.ImageField(upload_to='services/', null=False, blank=True)
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='services', verbose_name=_('language'), null=True, blank=True)

    url = models.URLField(null=False, blank=True)
    description = models.TextField(null=True, blank=False)
    create_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title


    @property
    def get_self_or_services_lang(self):
        # check are language existin Language model
        try:
            lang = Language.objects.get(code=get_language())
        except Language.DoesNotExist: # if not retrun default title
            return self
                    
        if self.language == lang:
            return self
        
        services_lang = self.services_lang.filter(language = lang)
        
        if services_lang:
            return services_lang.get()
        
        return self

    def get_titles(self):
        return self.get_self_or_services_lang.title
    
    def get_descriptions(self):
        return self.get_self_or_services_lang.description
    
   # def get_categories(self):
   #     return self.get_self_or_services_lang.categories
    
    def get_language_codes(self):
        return self.get_self_or_services_lang.language.code
              
##
class TranslateTittle(models.Model):
    services = models.ForeignKey(Services, on_delete=models.CASCADE, related_name='services_lang', verbose_name=_('services'))
    title = models.CharField(_('title'), max_length=100)
    description = models.TextField(_('description'), max_length=4000)
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='services_lan', verbose_name=_('language'))
    active = models.BooleanField(_('active'), default=True, choices=active_field_choices)

    def __str__(self):
        return self.title
 





##
class Brands(models.Model):
    image = models.ImageField(upload_to='Brands/', null=False, blank=True)
    url = models.URLField(null=False, blank=True)
    create_at = models.DateTimeField(auto_now=True)


   

project/dashboard/templates/dashboard/add_user.html
{% extends 'layouts/base.html' %}
{% block title %}اضافة مسؤول اداري{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block body %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content" >
        <div class="container-fluid " >
            <div class="row">
                <div class="col-12 mb-3">  
                    <div id="content-wrapper">
                        <div class=" " style="margin-top: 10px;" >
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                <a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i> الصفحة الرئيسية </a></li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url 'dashboard:accounts' %}"> المستخدمين</a>
                                </li>
                                <li class="breadcrumb-item active">
                                    <a href="">اضافة </a>
                                </li>
                            </ol>
                            {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}
                            <div class="card mb-3">
                                <div class="card-header">
                                    <i class="fas fa-table text-warning"></i>
                                        Details Of User
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12"> 
                                            <form action="{% url 'dashboard:accounts_create'%}" method="post">
                                                {% csrf_token %}
                                                <div class="card-body">
                                                    {% if form.errors %}
                                                    <div class="error-message text-center alert alert-danger alert-dismissible" role="alert">
                                                        <span class="">{{ form.username.errors }}</span>
                                                        <span class="">{{ form.email.errors }}</span>
                                                        <span class="">{{ form.password1.errors }}</span>
                                                        <span class="">{{ form.password2.errors }}</span>
                                                        <hr>
                                                    </div>
                                                    {% endif %}                                             
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="form-group">
                                                                {{ form|crispy }}
                                                            </div>
                                                        </div>
                                                        <div class="col-12">
                                                            <button type="submit" class="btn btn-primary btn-block">اضافة مستخدم</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}
{% block javascript %}
    <script type="text/javascript">
        $("#id_username").attr("placeholder", "Enter Username");
        $("#id_password").attr("placeholder", "Enter Password");
    </script>
{% endblock %}

project/dashboard/templates/dashboard/category.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} المشاريع{% endblock %}

{% block body %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md-12 ">
            <div class=" " style="margin-top: 10px;" > 
              <ol class="breadcrumb ">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i>الصفحة الرئيسية</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'dashboard:category' %}">المشاريع</a></li>
              </ol>          
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                  {{ message }}
              </div>
            {% endfor %}
      <!-- Default box -->
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title"></h3>
                  <div class="card-tools">
                    <a href="{% url 'dashboard:category_add'%} " class="btn btn-success pull-left "><i class="fa fa-plus"></i>اضافة</a>
                  </div>
                </div>
                <div class="card-body p-0 " >
                  <table class="table table-striped projects" style="overflow-x: auto;">
                      <thead>
                          <tr>
                              <th style="width: 1%">
                                  #
                              </th>
                              <th style="width: 35%">
                                  اسم
                              </th>
                              <th style="width: 10%">
                                  صورة
                              </th>
                              <th style="width:35%;" class="text-center">
                                  آخر تحديث
                              </th>
                              <th>
                                تحرير
                              </th>
                              <th>
                                حذف
                              </th>
                          </tr>
                      </thead>
                      <tbody>
                        {% for x in category %}
                          <tr>
                              <td>
                                {{ x.id }}
                              </td>
                              <td>
                                    {{ x.name }}                               
                              </td>
                              <td>
                                  <ul class="list-inline">
                                      <li class="list-inline-item">
                                          <img alt="Avatar" class="table-avatar" src="{{ x.image.url }}">
                                      </li>
                                  </ul>
                              </td>                    
                              <td class="project-state text-center" >
                                {{ x.create_at }}
                              </td>
                              <td class="project-actions text-right">                   
                                  <a class="btn btn-info btn-sm" href="{% url 'dashboard:category_edite' x.id %}">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    تعديل
                                </a>

                                  
                              </td>
                              <td>

                                <a class="btn btn-danger btn-sm" href="{% url 'dashboard:category_delete' x.id %}">
                                  <i class="fas fa-trash">
                                  </i>
                                  حذف
                              </a>
                              </td>
                           
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
          </div>
        </div>
      </div>
      </div>
            <!-- /.حذف -->
      <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">هل أنت متأكد؟</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% for x in project %}
            <div class="modal-body">
              <p>أأنت متأكد أنك تريد حذف العنصر المحدد؟ جميع العناصر المرتبطة بها سيتم حذفها:&hellip;</p>
            </div>
            <div class="modal-footer justify-content-between">
              <a class="delete" href="{% url 'dashboard:project_delete' x.id %}" >
              <button type="button" class="btn btn-primary">نعم أنا متأكد</button>
              </a>
              {% endfor %}
              <button type="button" class="btn btn-default" data-dismiss="modal"> لا ترجوع للخلف</button>
            
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.card -->
  </section>
    <!-- /.content -->
  </div>
{% endblock %}

project/dashboard/templates/dashboard/category_add.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}اضافة مشروع{% endblock %}
{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <section class="content">
        <div class="container-fluid">
          
          <div class="row ">
              <div class="col-md-12" style="margin-top: 10px;">
                <ol class="breadcrumb ">
                  <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i> الصفحة الرئيسية</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'dashboard:category' %}">المشاريع</a></li>
                  <li class="breadcrumb-item active">اضافة</li>
                </ol>
                    {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    {{ message }}
                </div>
                  {% endfor %}
                <div class="card ">
                    <div class="card-header">
                        <h3 class="card-title">General</h3> 
                    </div>
                    <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                  <div class="form-group">
                                      {{form|crispy}}
                                      {{form.media}}
                                    </div>
                               </div>  
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary btn-block">حفظ التغير </button>
                            </div>
                          </div>
                    </form>
                  </div>
                </div>
              </div>
          </div>
      </div>
      </section>
    </div>
{% endblock body %}

project/dashboard/templates/dashboard/confirm_delete.html
{% extends 'layouts/base.html' %}
{% load i18n %}
{% block body %}
<div class="content-header">
  <legend>
    {% trans 'delete' %} {{object}}
  </legend>
</div>
<p>{% trans 'Are You Sure You Want Delete' %}'{{object}}'</p>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete it" class="btn info">
  <a href="
  {% if 'comment' in request.path %}
    {% url 'dashboard:comments' %}  
  {% elif 'post' in request.path %}    
    {% url 'dashboard:posts' %}
  {% elif 'category' in request.path %}
    {% url 'dashboard:categories' %}
  {% else %}
    {% url 'dashboard:accounts' %}
  {% endif %}
  " class="btn info">{% trans 'no' %}</a>
</form>
{% endblock content  %}

project/dashboard/templates/dashboard/page_edite.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} تعديل {{form.title}} {% endblock %}
{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content">
        <div class="container-fluid">
          <div class="row ">
              <div class="col-md-12" style="margin-top: 10px;">
              <ol class="breadcrumb ">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}"><i class="nav-icon fas fa-home"></i>الصفحة الرئيسية</a></li>
                <li class="breadcrumb-item"><a href="{% url 'dashboard:page' %}">المقالات</a></li>
                <li class="breadcrumb-item active">{{objects.title}}</li>
              </ol>
              {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                {{ message }}
            </div>
              {% endfor %}
                <div class="card ">
                    <div class="card-header">
                        <h3 class="card-title">General</h3>
                       <div class="card-tools">
                          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                              <i class="fas fa-minus"></i>
                          </button>
                        </div>
                    </div>
                    <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                  <div class="form-group">
                                      {{form|crispy}}
                                      {{form.media}}
                                  </div>
                                </div> 
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary btn-block">حفظ التغير </button>
                                </div>
                          </div>
                    </form>
                  </div>
                </div>
            </div>
        </div>
      </div>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock body %}